<?php

use Drupal\commerce_currencies\Uninstaller;
use Drupal\commerce_product\Entity\ProductVariationTypeInterface;
use Drupal\Core\Batch\BatchBuilder;
use Drupal\Core\Entity\{Display\EntityDisplayInterface, Display\EntityFormDisplayInterface, Display\EntityViewDisplayInterface, EntityDisplayRepository, EntityTypeInterface, Entity\EntityFormDisplay, Entity\EntityViewDisplay, EntityFormInterface};
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\CurrentRouteMatch;
use Drupal\system\Form\ModulesUninstallConfirmForm;
use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function commerce_currencies_help($route_name, CurrentRouteMatch $route_match) {
  switch ($route_name) {
    case 'help.page.commerce_currencies':
      $output = '<h3>' . t('After installation') . '</h3>';
      $output .= '<p>' . t('Upon installation, existing commerce entities (product types, variations, etc) were scanned and the original, single-currency <kbd>commerce_price</kbd> fields got replaced with new, multi-currency variants. Widgets (single or list price) and display settings were also modified. Previously existing prices were migrated to the new setup. In a stock Commerce store, this already means fully functional multi-currency operation, you don\'t need any other change.') . '</p>';
      $output .= '<p>' . t('If you use custom entities, either created in the UI or from code, make sure you replace old <kbd>commerce_price</kbd> fields with the new <kbd>commerce_currencies_price</kbd> type. They appear in the usual field UI among the Commerce related field types as <em>Price (multi-currency)</em>.') . '</p>';
      $output .= '<p>' . t('Also take care of custom theme templates referencing the old <kbd>price</kbd> and <kbd>list_price</kbd> fields, the new, automatically created ones have the names <kbd>commerce_currencies_price</kbd> and <kbd>commerce_currencies_list_price</kbd>.') . '</p>';
      return $output;
  }
}

//======================================================================
// INSTALLATION, DATA MIGRATION AND UNINSTALLATION
//======================================================================

/**
 * Implements hook_locale_translation_projects_alter().
 */
function commerce_currencies_locale_translation_projects_alter(&$projects) {
  $folder = \Drupal::service('extension.list.module')->getPath('commerce_currencies');
  $projects['commerce_currencies'] = [
    'info' => [
      'interface translation server pattern' => $folder . '/translations/%language.po',
    ],
  ];
}

/**
 * Implements hook_entity_base_field_info().
 *
 * Attaches multi-currency 'commerce_price' fields to all product variation bundles.
 */
function commerce_currencies_entity_base_field_info(EntityTypeInterface $type) {
  if ($type->id() == 'commerce_product_variation') {
    $fields = [];
    $fields['commerce_currencies_list_price'] = BaseFieldDefinition::create('commerce_currencies_price')
      ->setLabel(t('List price'))
      ->setDescription(t('Multi-currency price'))
      ->setCardinality(1)
      ->setDisplayOptions('form', ['type' => 'commerce_currencies_price_list'])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('view', ['type' => 'commerce_currencies_price_default'])
      ->setDisplayConfigurable('view', TRUE);

    $fields['commerce_currencies_price'] = BaseFieldDefinition::create('commerce_currencies_price')
      ->setLabel(t('Price'))
      ->setDescription(t('Multi-currency price'))
      ->setCardinality(1)
      ->setDisplayOptions('form', ['type' => 'commerce_currencies_price_default'])
      ->setDisplayConfigurable('form', TRUE)
      ->setDisplayOptions('view', ['type' => 'commerce_currencies_price_default'])
      ->setDisplayConfigurable('view', TRUE);

    return $fields;
  }
}

/**
 * Hides single-currency 'commerce_price' fields and replaces them with multi-currency 'commerce_currencies_price' fields.
 */
function _commerce_currencies_replace_form_display(EntityFormDisplayInterface $display) {
  $done = FALSE;
  foreach ($display->getComponents() as $name => $options) {
    switch ($name) {
      case 'list_price':
        if ($options['region'] == 'content') {
          $display->setComponent('commerce_currencies_' . $name, [
            'region' => 'content',
            'type' => 'commerce_currencies_price_list',
            'settings' => $options['settings'],
            'third_party_settings' => $options['third_party_settings'],
            'weight' => intval($options['weight']),
          ]);
          $display->removeComponent($name);
          $done = TRUE;
        }
        break;
      case 'price':
        if ($options['region'] == 'content') {
          $display->setComponent('commerce_currencies_' . $name, [
            'region' => 'content',
            'type' => 'commerce_currencies_price_default',
            'settings' => $options['settings'],
            'third_party_settings' => $options['third_party_settings'],
            'weight' => intval($options['weight']),
          ]);
          $display->removeComponent($name);
          $done = TRUE;
        }
        break;
    }
  }
  return $done;
}

/**
 * Hides single-currency 'commerce_price' fields and replaces them with multi-currency 'commerce_currencies_price' fields.
 */
function _commerce_currencies_replace_view_display(EntityViewDisplayInterface $display) {
  $done = FALSE;
  foreach ($display->getComponents() as $name => $options) {
    switch ($name) {
      case 'list_price':
      case 'price':
        if ($options['region'] == 'content') {
          $display->setComponent('commerce_currencies_' . $name, [
            'region' => 'content',
            'type' => 'commerce_currencies_price_default',
            'label' => $options['label'],
            'settings' => $options['settings'],
            'third_party_settings' => $options['third_party_settings'],
            'weight' => intval($options['weight']),
          ]);
          $display->removeComponent($name);
          $done = TRUE;
        }
        break;
    }
  }
  return $done;
}

/**
 * Hides multi-currency 'commerce_currencies_price' fields and replaces them with single-currency 'commerce_price' fields.
 * Called before uninstallation.
 */
function _commerce_currencies_restore_display(EntityDisplayInterface $display) {
  $done = FALSE;
  foreach ($display->getComponents() as $name => $options) {
    switch ($name) {
      case 'commerce_currencies_list_price':
      case 'commerce_currencies_price':
        if ($options['region'] == 'content') {
          $display->setComponent(str_replace('commerce_currencies_', '', $name), [
            'region' => 'content',
            'label' => isset($options['label']) ? $options['label'] : NULL,
            'settings' => $options['settings'],
            'third_party_settings' => $options['third_party_settings'],
            'weight' => intval($options['weight']),
          ]);
          $display->removeComponent($name);
          $done = TRUE;
        }
        break;
    }
  }
  return $done;
}

/**
 * Implements hook_ENTITY_TYPE_insert() for 'commerce_product_variation_type'.
 *
 * Delegate task to a shutdown function because this runs BEFORE the entity gets actually saved to the database.
 */
function commerce_currencies_commerce_product_variation_type_insert(ProductVariationTypeInterface $type) {
  drupal_register_shutdown_function('_commerce_currencies_commerce_product_variation_type_postinsert', $type);
}

/**
 * Hides single-currency 'commerce_price' fields on the default view/form modes of new product variation types.
 */
function _commerce_currencies_commerce_product_variation_type_postinsert(ProductVariationTypeInterface $type) {
  /** @var EntityDisplayRepository $display_repository */
  $display_repository = \Drupal::service('entity_display.repository');

  $display = $display_repository->getFormDisplay('commerce_product_variation', $type->id());
  _commerce_currencies_replace_form_display($display);
  $display->save();

  $display = $display_repository->getViewDisplay('commerce_product_variation', $type->id());
  _commerce_currencies_replace_view_display($display);
  $display->save();
}

/**
 * Implements hook_ENTITY_TYPE_presave() for 'entity_form_display'.
 *
 * Hides single-currency 'commerce_price' fields on all new product variation forms.
 */
function commerce_currencies_entity_form_display_presave(EntityFormDisplayInterface $display) {
  if (!$display->isSyncing() && $display->getTargetEntityTypeId() == 'commerce_product_variation' && $display->isNew()) {
    if (_commerce_currencies_replace_form_display($display)) {
      \Drupal::messenger()->addStatus(t('Price fields replaced with multi-currency ones in form display "@type.@bundle.@mode".', [
        '@type' => $display->getTargetEntityTypeId(),
        '@bundle' => $display->getTargetBundle(),
        '@mode' => $display->getMode()
      ]), TRUE);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for 'entity_view_display'.
 *
 * Hides single-currency 'commerce_price' fields on all new product variation displays.
 */
function commerce_currencies_entity_view_display_presave(EntityViewDisplayInterface $display) {
  if (!$display->isSyncing() && $display->getTargetEntityTypeId() == 'commerce_product_variation' && $display->isNew()) {
    if (_commerce_currencies_replace_view_display($display)) {
      \Drupal::messenger()->addStatus(t('Price fields replaced with multi-currency ones in view display "@type.@bundle.@mode".', [
        '@type' => $display->getTargetEntityTypeId(),
        '@bundle' => $display->getTargetBundle(),
        '@mode' => $display->getMode()
      ]), TRUE);
    }
  }
}

function _commerce_currencies_access_protected($object, string $property) {
  $reflection = new ReflectionClass($object);
  $property = $reflection->getProperty($property);
  $property->setAccessible(true);
  return $property->getValue($object);
}

/**
 * Implements hook_form_FORM_ID_alter() for 'system_modules_uninstall_confirm_form'.
 *
 * Removes own fields from dependency list.
 * Our own Uninstaller will restore them before uninstallation, so they won't get deleted.
 */
function commerce_currencies_form_system_modules_uninstall_confirm_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  /** @var ModulesUninstallConfirmForm $confirm_form */
  $confirm_form = $form_state->getBuildInfo()['callback_object'];
  $modules = _commerce_currencies_access_protected($confirm_form, 'modules');
  if (in_array('commerce_currencies', $modules)) {
    unset($form['entity_updates'], $form['entity_deletes']);
    Uninstaller::addDependencyLists($form, $modules);
  }
}

/**
 * Implements hook_modules_installed().
 *
 * Replaces single-currency view and form fields with multi-currency ones.
 * Migrates single-currency prices to the multi-currency fields.
 */
function commerce_currencies_modules_installed(array $modules, bool $is_syncing) {
  if (!$is_syncing && in_array('commerce_currencies', $modules)) {
    $ids = \Drupal::entityQuery('entity_form_display')
      ->condition('id', 'commerce_product_variation.', 'STARTS_WITH')
      ->execute();
    if (!empty($ids)) {
      foreach (EntityFormDisplay::loadMultiple($ids) as $display) {
        _commerce_currencies_replace_form_display($display);
        $display->save();
      }
    }

    $ids = \Drupal::entityQuery('entity_view_display')
      ->condition('id', 'commerce_product_variation.', 'STARTS_WITH')
      ->execute();
    if (!empty($ids)) {
      foreach (EntityViewDisplay::loadMultiple($ids) as $display) {
        _commerce_currencies_replace_view_display($display);
        $display->save();
      }
    }

    $batch_builder = (new BatchBuilder())
      ->setErrorMessage(t('Error copying existing single-currency prices'))
      ->setFinishCallback('commerce_currencies_batch_finished')
      ->addOperation('commerce_currencies_batch_migration', []);
    batch_set($batch_builder->toArray());
  }
}

/**
 * Implements callback_batch_operation().
 */
function commerce_currencies_batch_migration(&$context) {
  $connection = \Drupal::database();

  if (empty($context['sandbox'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['current_id'] = 0;
    $context['sandbox']['max'] = $connection->query('SELECT COUNT([variation_id]) FROM {commerce_product_variation_field_data}')->fetchField();
    $context['results'] = 0;
  }

  $records = $connection->select('commerce_product_variation_field_data', 'd')
    ->fields('d', [
      'variation_id',
      'list_price__number',
      'list_price__currency_code',
      'price__number',
      'price__currency_code',
      'commerce_currencies_list_price',
      'commerce_currencies_price',
    ])
    ->condition('variation_id', $context['sandbox']['current_id'], '>')
    ->range(0, 20)
    ->orderBy('variation_id', 'ASC')
    ->execute();

  foreach ($records as $record) {
    $connection->update('commerce_product_variation_field_data')
      ->fields([
        'commerce_currencies_list_price' => serialize([$record->list_price__currency_code => $record->list_price__number]),
        'commerce_currencies_price' => serialize([$record->price__currency_code => $record->price__number]),
      ])
      ->condition('variation_id', $record->variation_id)
      ->execute();
    $context['sandbox']['progress']++;
    $context['results']++;
    $context['sandbox']['current_id'] = $record->variation_id;
    $context['message'] = t('Migrating single-currency prices to multi-currency fields.');
  }

  if ($context['sandbox']['progress'] != $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

/**
 * Implements callback_batch_finished().
 *
 * Set result message.
 */
function commerce_currencies_batch_finished(bool $success, $results, $operations, $elapsed) {
  if ($success) {
    \Drupal::messenger()->addStatus(t('Price fields replaced with multi-currency ones, single-currency prices migrated.'));
  } else {
    \Drupal::messenger()->addError(t('An error occurred while setting up the multi-currency prices.'));
  }
}

//======================================================================
// CURRENCY SELECTION
//======================================================================

/**
 * Implements hook_ENTITY_update() for 'user'.
 *
 * Store a cookie for rapid currency selection.
 */
function commerce_currencies_user_update(UserInterface $user) {
  foreach ($user->getFieldDefinitions() as $field) {
    if ($field->getType() == 'commerce_currencies_preferred') {
      $currency_code = $user->get($field->getName())->value;
      setrawcookie('commerce_currencies_currency_code', rawurlencode($currency_code), [
        'expires' => 0,
        'path' => '/',
        'samesite' => 'Strict',
      ]);
      return;
    }
  }
}

//======================================================================
// USER INTERFACE MODIFICATIONS
//======================================================================

/**
 * Implements hook_form_BASE_FORM_ID_alter() for 'commerce_store_form'.
 * 
 * Enlarge the listboxes on the store editing forms for convenience.
 * Add "EU countries" button for convenience.
 */
function commerce_currencies_form_commerce_store_form_alter(&$form, FormStateInterface $form_state,  $form_id) {
  if (isset($form['billing_countries'])) {
    $form['billing_countries']['widget']['#size'] = 12;
  }
  if (isset($form['shipping_countries'])) {
    $form['shipping_countries']['widget']['#size'] = 12;
  }
  if (isset($form['tax_registrations'])) {
    $form['tax_registrations']['widget']['#size'] = 24;
    $form['tax_registrations_eu'] = [
      '#type' => 'checkbox',
      '#title' => t('EU countries'),
      '#weight' => 100,
      '#group' => 'tax_settings',
    ];
    array_unshift($form['actions']['submit']['#submit'], '_commerce_currencies_form_commerce_store_form_submit');
  }
}

function _commerce_currencies_form_commerce_store_form_submit(&$form, FormStateInterface $form_state) {
  if ($form_state->getValue('tax_registrations_eu') == TRUE) {
    $form_state->setValue('tax_registrations', [
      ['value' => 'AT'],
      ['value' => 'BE'],
      ['value' => 'BG'],
      ['value' => 'HR'],
      ['value' => 'CY'],
      ['value' => 'CZ'],
      ['value' => 'DK'],
      ['value' => 'EE'],
      ['value' => 'FI'],
      ['value' => 'FR'],
      ['value' => 'DE'],
      ['value' => 'GR'],
      ['value' => 'HU'],
      ['value' => 'IE'],
      ['value' => 'IT'],
      ['value' => 'LV'],
      ['value' => 'LT'],
      ['value' => 'LU'],
      ['value' => 'MT'],
      ['value' => 'NL'],
      ['value' => 'PL'],
      ['value' => 'PT'],
      ['value' => 'RO'],
      ['value' => 'SK'],
      ['value' => 'SI'],
      ['value' => 'ES'],
      ['value' => 'SE'],
    ]);
  }
}

/**
 * Implements hook_element_info_alter().
 * 
 * Add a post-processing function to alter the commerce_conditions form element.
 */
function commerce_currencies_element_info_alter(array &$info) {
  if (isset($info['commerce_conditions'])) {
    array_splice($info['commerce_conditions']['#process'], 2, 0, '_commerce_currencies_element_commerce_conditions_alter');
  }
}

/**
 * Add a warning to use the Current currency conditions instead.
 */
function _commerce_currencies_element_commerce_conditions_alter(array &$element, FormStateInterface $form_state, array &$complete_form) {
  if (isset($element['order']['order_currency'])) {
    $element['order']['order_currency']['enable']['#description'] = t('You should prefer the Current currency condition for proper multi-currency operation.');
  }
  return $element;
}
